### PR TITLE
fix: should unescape underscores back from markdown strict

### PR DESCRIPTION
**Pull request by belonesox**
Lets consider include line 

```
!include somefolder/filename_with_underscores.md
```

We got following json `para.json` 
[para-json.zip](https://github.com/DCsunset/pandoc-include/files/15046970/para-json.zip)

when we call `inner_convert_text`  we run pandoc like that
```
    pandoc --from=json --to=markdown_strict ./para.json 
```

For me pandoc 3.1.12.3 returns 

```
!include somefolder/filename\_with\_underscores.md
```
So we have to unescape underscores back, or we will got `[WARNING] Included file not found:` later.

### CODE REVIEW

**Review by DCsunset — APPROVED** [review]

**Comment by DCsunset** [comment]
Thanks. LGTM

**Comment by belonesox** [comment]
> could you reword your commit using the format `fix: ...`?

I tried, looks I reword also another commit. :(

**Comment by DCsunset** [comment]
Your changes are gone now. I'm not sure what you did. But you could have done it with `git commit --amend`. Could you clean up your branch and add your changes back?

**Comment by belonesox** [comment]
Sorry, something wrong with my git-fu, just push next pull here https://github.com/DCsunset/pandoc-include/pull/48

**Comment by DCsunset** [comment]
Thanks. Merged #48 already.

**Pull request closed without merging**
