### PR TITLE
fix: make temporary filename unique.

### PR DESCRIPTION
**Pull request by W-Floyd**
This makes it possible to run pandoc with GNU parallel.

### CODE REVIEW

**Comment by DCsunset** [comment]
Hello, thanks for your contributions.
This PR is similar to #10.

The temp file now is used to share config between multiple executions of `pandoc_include.py`,
i.e. the subsequent executions of `pandoc_include.py` need to share the same temp file of its parent.
I think a unique temp file will break the original functionaily.

**Comment by W-Floyd** [comment]
I guess my understanding of the program is incorrect.

What I am trying to achieve is making it possible to run pandoc in parallel, while still using this filter. Currently, if I do so, it overwrites the same file for different runs, which kills it.

**Comment by W-Floyd** [comment]
Running the test produces the same outputs with the change I added. Why might this be?

**Comment by DCsunset** [comment]
The test doesn't cover this feature, so the result might be the same in this case.

This feature mainly provides convenience for `pandoc-options`.
For example, if you want to use some other filters when including other files, it would be cumbersome to specify the `pandoc-options` in every included file. So by default, the included files will inherit their parents' `pandoc-options`.

As for parallelism, I don't know whether there's a good workaround. Do you have any idea?

**Comment by W-Floyd** [comment]
Ah I see, that makes sense.

I'll admit to not being familiar at all with pandoc filters, but I take it that it's not possible to pass a filename on down the chain to subsequent runs of the filter? Ideally, could one set a filename on the first run, and propagate that?

**Comment by DCsunset** [comment]
I haven't found a feasible way to run a pandoc filter with some argument, especially inside a filter.
A possible solution is not to use a temp file by default and only use it when changing the `pandoc-options`.
In most cases, the `pandoc-options` won't be changed, so you could run it in parallel.

However, when you change the `pandoc-options`, you cannot run it in parallel. What do you think of this solution?

**Comment by W-Floyd** [comment]
That sounds like a reasonable compromise. Too bad there's no way to pass options, but I understand. Thanks for your work!
________________________________

**Comment by DCsunset** [comment]
I have applied the above workaround in the master branch.
Could you give the command to run it with GNU parallel so I could test it?

**Pull request closed without merging**
